// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWYJHrVwBjQ3TgSUOANliAKPItsP8Jhzw',
    appId: '1:644283074697:web:a09090ff3f3113fb101e58',
    messagingSenderId: '644283074697',
    projectId: 'infinity-messenger-170b0',
    authDomain: 'infinity-messenger-170b0.firebaseapp.com',
    storageBucket: 'infinity-messenger-170b0.appspot.com',
    measurementId: 'G-PRP24Z2VVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTcqec9925CT1-61Q6ysnUwMZ6Rw44qVQ',
    appId: '1:644283074697:android:859371f141ea4278101e58',
    messagingSenderId: '644283074697',
    projectId: 'infinity-messenger-170b0',
    storageBucket: 'infinity-messenger-170b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_PSgTtcmt4SrVqoSz3ekqIX2o6avwe4I',
    appId: '1:644283074697:ios:aac05b45ea36f1c2101e58',
    messagingSenderId: '644283074697',
    projectId: 'infinity-messenger-170b0',
    storageBucket: 'infinity-messenger-170b0.appspot.com',
    iosBundleId: 'com.example.infinityMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_PSgTtcmt4SrVqoSz3ekqIX2o6avwe4I',
    appId: '1:644283074697:ios:092be3245b9aec28101e58',
    messagingSenderId: '644283074697',
    projectId: 'infinity-messenger-170b0',
    storageBucket: 'infinity-messenger-170b0.appspot.com',
    iosBundleId: 'com.example.infinityMessenger.RunnerTests',
  );
}
